# Generated by Django 4.1.4 on 2023-01-03 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='HotelDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.IntegerField(default=0)),
                ('received', models.IntegerField(default=0)),
                ('damaged', models.IntegerField(default=0)),
                ('returned', models.IntegerField(default=0)),
                ('transferred', models.IntegerField(default=0)),
                ('min_level', models.IntegerField(default=0)),
                ('max_level', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.hotel')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.item')),
            ],
        ),
        migrations.RenameModel(
            old_name='Designation',
            new_name='DesignationMaster',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddConstraint(
            model_name='iteminhotel',
            constraint=models.UniqueConstraint(fields=('hotel', 'item'), name='unique_item_of_hotel'),
        ),
    ]
