# Generated by Django 4.1.4 on 2023-01-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_remove_hoteldepartment_name_remove_item_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmaster',
            name='short_name',
            field=models.CharField(default=3.0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='short_name',
            field=models.CharField(default=4.0, max_length=3),
            preserve_default=False,
        ),
    ]
