# Generated by Django 4.1.4 on 2023-05-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_item_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('address', models.CharField(max_length=512)),
                ('contact_no', models.CharField(max_length=15)),
                ('gst_no', models.CharField(max_length=15)),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('remarks', models.CharField(blank=True, max_length=2048)),
            ],
        ),
    ]
