# Generated by Django 4.1.4 on 2023-05-07 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldepartment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.departmentmaster'),
        ),
        migrations.AlterField(
            model_name='hoteldepartment',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.hotel'),
        ),
    ]
