# Generated by Django 4.1.4 on 2023-05-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_alter_hoteldepartment_department_and_more'),
        ('configuration', '0008_alter_hoteldepartment_hotel'),
    ]

    operations = [
    ]
