# Generated by Django 4.1.4 on 2023-05-12 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_merge_20230507_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldepartment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_department', to='configuration.departmentmaster'),
        ),
        migrations.AlterField(
            model_name='hoteldepartment',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_department', to='configuration.hotel'),
        ),
    ]
