# Generated by Django 4.1.4 on 2023-01-05 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0004_remove_hoteldepartment_name_remove_item_item_type_and_more'),
        ('operation', '0002_itemreturned_itemreceived_itemdamaged'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdamaged',
            name='remarks',
            field=models.CharField(default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='itemreceived',
            name='remarks',
            field=models.CharField(default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='itemreturned',
            name='remarks',
            field=models.CharField(default='', max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='ItemTransferred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_transferred', models.IntegerField(default=0)),
                ('remarks', models.CharField(default='', max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_transferred_created_by', to=settings.AUTH_USER_MODEL)),
                ('from_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_department', to='configuration.departmentmaster')),
                ('from_hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_hotel', to='configuration.hotel')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.item')),
                ('to_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_department', to='configuration.departmentmaster')),
                ('to_hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_hotel', to='configuration.hotel')),
            ],
        ),
    ]
