# Generated by Django 4.1.4 on 2023-01-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_itemdamaged_remarks_itemreceived_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdamaged',
            name='opening_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemreceived',
            name='opening_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemreturned',
            name='opening_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemtransferred',
            name='opening_balance',
            field=models.IntegerField(default=0),
        ),
    ]
