# Generated by Django 4.1.4 on 2023-05-04 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_vendor'),
        ('operation', '0008_itemdamaged_damaged_on_itemreceived_received_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdamaged',
            name='batch_no',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='itemreceived',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.vendor'),
        ),
        migrations.AddField(
            model_name='itemreturned',
            name='batch_no',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='itemtransferred',
            name='batch_no',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='itemreceived',
            name='batch_no',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
