# Generated by Django 4.1.4 on 2023-05-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_itemdamaged_batch_no_itemreceived_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreturned',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemreturned',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
