# Generated by Django 4.1.4 on 2023-05-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_itemreturned_expiry_date_itemreturned_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdamaged',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemdamaged',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
