# Generated by Django 4.1.4 on 2023-05-12 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_alter_hoteldepartment_department_and_more'),
        ('operation', '0012_itemtransferred_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableItemQuantitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.IntegerField(default=0)),
                ('quantity_received', models.IntegerField(default=0)),
                ('quantity_returned', models.IntegerField(default=0)),
                ('quantity_damaged', models.IntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.item')),
            ],
        ),
        migrations.AddConstraint(
            model_name='availableitemquantitysnapshot',
            constraint=models.UniqueConstraint(fields=('item',), name='unique_item'),
        ),
    ]
